prometheus:
  enabled: true

grafana:
  enabled: true
  adminUser: admin
  adminPassword: admin
  service:
    type: ClusterIP

serviceMonitor:
  enabled: true
  namespace: monitoring
  selector:
    matchLabels:
      app: prometheus
  endpoints:
    - port: web
      path: /metrics

alertmanager:
  enabled: false
