apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-traefik
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-traefik
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-traefik
    spec:
      containers:
        - name: traefik
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
